# -*- coding: utf-8 -*-
"""Student- Grade- Calculator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18irv0L2_tiPg9vxmugeTCPBSMtctfw8n
"""

# Creating a students'Grade Calculator
# Taking inputs from the user
name = input("Enter your name: ")
English = int(input("Enter the marks of English: "))
Maths = int(input("Enter the marks of Maths: "))
Science = int(input("Enter the marks of Science:"))
History = int(input("Enter the marks of History: "))
Geography = int(input("Enter the marks of Geography: "))
Sum = English + Maths + Science + History + Geography
Average = Sum/5
print("-----Results------")
print("Total Marks:", Sum)
print("Average Marks:", Average)
if Average >= 90:
    print("Grade: A")
elif Average >= 80:
    print("Grade: B")
elif Average >= 70:
    print("Grade: C")
elif Average >= 60:
    print("Grade: D")
else:
    print("Grade: F")

# outputs


# Enter your name :
# Enter the marks of English:
#Enter the marks of Maths:
#Enter the marks of Science:
#Enter the marks of History:
# Enter the marks of Geography:
#------Results-----
#Total marks:
#Average marks:
#Grade: